

# -------------------------------------------------------------
# 1️⃣ Choose a base image that already contains Python.
# -------------------------------------------------------------
FROM python:3.12-slim-bookworm
RUN echo "1PROJECT_NAME = '${PROJECT_NAME}'"
# tells Docker to accept the build‑arg
ARG PROJECT_NAME=PokemonETL # Fallback
ENV PROJECT_NAME=${PROJECT_NAME}
RUN echo "2PROJECT_NAME = '${PROJECT_NAME}'"

# -------------------------------------------------------------
# 2️⃣ Install OS‑level packages that some wheels need.
# -------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc libpq-dev curl && \
    rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------
# 3️⃣ Create a non‑root user (good practice for containers)
# -------------------------------------------------------------
ARG USERNAME=appuser
ARG UID=1000
ARG GID=1000
RUN groupadd -g ${GID} ${USERNAME} && \
    useradd -m -u ${UID} -g ${GID} -s /bin/bash ${USERNAME}


# -------------------------------------------------------------
# 4️⃣ Copy the source tree into /app and install deps
# -------------------------------------------------------------
WORKDIR /PokemonETL
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p /PokemonETL/app/logs && chown -R 1000:1000 /PokemonETL/app/logs

# Copy the actual Python package (the `app/` folder)
COPY app/ /PokemonETL/app/
COPY .env /PokemonETL
COPY logging_config.yaml /PokemonETL

RUN echo "Fixing permissions on /PokemonETL..." && \
    chown -R "${UID}:${GID}" /PokemonETL

# -------------------------------------------------------------
# 5️⃣ Switch to the non‑root user
# -------------------------------------------------------------
USER ${USERNAME}

# should help with unbuffered output,
ENV PYTHONUNBUFFERED=1

# -------------------------------------------------------------
# 6️⃣ Default command – can be overridden in compose if you like
# -----------------------------------------------
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]